[2025-04-07T03:51:03.237+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T03:51:03.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task manual__2025-04-07T03:45:55.520076+00:00 [queued]>
[2025-04-07T03:51:03.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task manual__2025-04-07T03:45:55.520076+00:00 [queued]>
[2025-04-07T03:51:03.382+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-07T03:51:03.420+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-04-07 03:45:55.520076+00:00
[2025-04-07T03:51:03.437+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'manual__2025-04-07T03:45:55.520076+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmpc6u2vfax']
[2025-04-07T03:51:03.445+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask spark_streaming_task
[2025-04-07T03:51:03.450+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=26616) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-07T03:51:03.452+0000] {standard_task_runner.py:64} INFO - Started process 26620 to run task
[2025-04-07T03:51:03.577+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task manual__2025-04-07T03:45:55.520076+00:00 [running]> on host 42c88f897c40
[2025-04-07T03:51:03.732+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T03:45:55.520076+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T03:45:55.520076+00:00'
[2025-04-07T03:51:03.742+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T03:51:03.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T03:51:03.793+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-04-07T03:51:03.823+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=manual__2025-04-07T03:45:55.520076+00:00, execution_date=20250407T034555, start_date=20250407T035103, end_date=20250407T035103
[2025-04-07T03:51:03.845+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 26620)
[2025-04-07T03:51:03.870+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-04-07T03:51:03.895+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
