[2025-04-07T02:52:33.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T02:52:35.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-04-07T02:52:35.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-04-07T02:52:35.377+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-07T02:52:36.827+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-01-01 00:00:00+00:00
[2025-04-07T02:52:37.212+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=22445) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-07T02:52:37.337+0000] {standard_task_runner.py:64} INFO - Started process 22449 to run task
[2025-04-07T02:52:37.263+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmpv2eh60i6']
[2025-04-07T02:52:37.435+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask spark_streaming_task
[2025-04-07T02:52:38.319+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host 42c88f897c40
[2025-04-07T02:52:40.283+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-04-07T02:52:40.287+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T02:52:40.385+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T02:52:40.387+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-04-07T02:52:40.471+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250407T025235, end_date=20250407T025240
[2025-04-07T02:52:40.553+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 22449)
[2025-04-07T02:52:40.611+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-04-07T02:52:40.662+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
