[2025-03-26T12:11:55.599+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T12:11:55.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:11:55.660+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:11:55.661+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T12:11:55.675+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-01-01 00:00:00+00:00
[2025-03-26T12:11:55.686+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmprd474qv6']
[2025-03-26T12:11:55.689+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask spark_streaming_task
[2025-03-26T12:11:55.689+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=6859) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T12:11:55.690+0000] {standard_task_runner.py:64} INFO - Started process 6860 to run task
[2025-03-26T12:11:55.745+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host d53f18eaa4d6
[2025-03-26T12:11:55.840+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-03-26T12:11:55.841+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T12:11:55.857+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T12:11:55.859+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-03-26T12:11:55.872+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250326T121155, end_date=20250326T121155
[2025-03-26T12:11:55.884+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 6860)
[2025-03-26T12:11:55.905+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-26T12:11:55.925+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T12:11:55.927+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-03-26T12:34:12.821+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T12:34:12.871+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:34:12.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:34:12.897+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T12:34:12.927+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-01-01 00:00:00+00:00
[2025-03-26T12:34:12.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmpb9g98a_d']
[2025-03-26T12:34:12.949+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask spark_streaming_task
[2025-03-26T12:34:12.961+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=592) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T12:34:12.963+0000] {standard_task_runner.py:64} INFO - Started process 596 to run task
[2025-03-26T12:34:13.041+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host 24f3bed66440
[2025-03-26T12:34:13.226+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-03-26T12:34:13.227+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T12:34:13.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T12:34:13.250+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-03-26T12:34:13.267+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250326T123412, end_date=20250326T123413
[2025-03-26T12:34:13.289+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 596)
[2025-03-26T12:34:13.340+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-26T12:34:13.389+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T12:34:13.405+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-03-26T13:13:26.321+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T13:13:26.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T13:13:26.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T13:13:26.363+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-26T13:13:26.372+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-01-01 00:00:00+00:00
[2025-03-26T13:13:26.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmptmca4u24']
[2025-03-26T13:13:26.379+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask spark_streaming_task
[2025-03-26T13:13:26.384+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=948) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:13:26.384+0000] {standard_task_runner.py:64} INFO - Started process 949 to run task
[2025-03-26T13:13:26.412+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host 39d8137af0c6
[2025-03-26T13:13:26.471+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-03-26T13:13:26.472+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T13:13:26.485+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T13:13:26.486+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-03-26T13:13:26.494+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250326T131326, end_date=20250326T131326
[2025-03-26T13:13:26.502+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 949)
[2025-03-26T13:13:26.517+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-26T13:13:26.534+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:13:26.535+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
