[2025-03-26T12:16:56.150+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T12:16:56.182+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:16:56.188+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:16:56.189+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-26T12:16:56.198+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-01-01 00:00:00+00:00
[2025-03-26T12:16:56.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmprs0vfdhm']
[2025-03-26T12:16:56.206+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask spark_streaming_task
[2025-03-26T12:16:56.207+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=7117) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T12:16:56.207+0000] {standard_task_runner.py:64} INFO - Started process 7118 to run task
[2025-03-26T12:16:56.239+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host d53f18eaa4d6
[2025-03-26T12:16:56.303+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-03-26T12:16:56.303+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T12:16:56.315+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T12:16:56.315+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-03-26T12:16:56.323+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250326T121656, end_date=20250326T121656
[2025-03-26T12:16:56.330+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 7118)
[2025-03-26T12:16:56.340+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-26T12:16:56.352+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T12:16:56.353+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-03-26T12:39:14.154+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T12:39:14.181+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:39:14.187+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T12:39:14.187+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-26T12:39:14.195+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-01-01 00:00:00+00:00
[2025-03-26T12:39:14.201+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmp_wdsi8uo']
[2025-03-26T12:39:14.203+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask spark_streaming_task
[2025-03-26T12:39:14.206+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=840) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T12:39:14.206+0000] {standard_task_runner.py:64} INFO - Started process 841 to run task
[2025-03-26T12:39:14.235+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host 24f3bed66440
[2025-03-26T12:39:14.293+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-03-26T12:39:14.294+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T12:39:14.304+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T12:39:14.305+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-03-26T12:39:14.312+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250326T123914, end_date=20250326T123914
[2025-03-26T12:39:14.319+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 841)
[2025-03-26T12:39:14.339+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-26T12:39:14.350+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T12:39:14.351+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-03-26T13:18:26.882+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-26T13:18:26.918+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T13:18:26.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-03-26T13:18:26.925+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-26T13:18:26.933+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): spark_streaming_task> on 2025-01-01 00:00:00+00:00
[2025-03-26T13:18:26.939+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kafka_spark_streaming', 'spark_streaming_task', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark_streaming.py', '--cfg-path', '/tmp/tmp5muy3l6q']
[2025-03-26T13:18:26.941+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask spark_streaming_task
[2025-03-26T13:18:26.944+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1217) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:18:26.944+0000] {standard_task_runner.py:64} INFO - Started process 1218 to run task
[2025-03-26T13:18:26.973+0000] {task_command.py:426} INFO - Running <TaskInstance: kafka_spark_streaming.spark_streaming_task scheduled__2025-01-01T00:00:00+00:00 [running]> on host 39d8137af0c6
[2025-03-26T13:18:27.030+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_spark_streaming' AIRFLOW_CTX_TASK_ID='spark_streaming_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-03-26T13:18:27.031+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-26T13:18:27.041+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-26T13:18:27.042+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_kafka_spark_streaming.py", line 12, in start_spark_streaming
    subprocess.run(["spark-submit", "./script/spark_streaming.py"])
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'spark-submit'
[2025-03-26T13:18:27.049+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kafka_spark_streaming, task_id=spark_streaming_task, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250326T131826, end_date=20250326T131827
[2025-03-26T13:18:27.056+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task spark_streaming_task ([Errno 13] Permission denied: 'spark-submit'; 1218)
[2025-03-26T13:18:27.077+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-26T13:18:27.089+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:18:27.090+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
